### ISSUE TITLE
How to interpret output file from classify_xgb.py

### ISSUE THREAD

**Issue by sbennett-cyber** [Shamir-Lab/4CAC#3]
Very exciting pipeline!

I would like to use the first step, classify_xgb.py, to identify if a contig comes from a eukaryote. Where can I find a description of how to interpret the results from this script? I know the first column is contig ID, but I am unclear about the other columns. Thanks!

**Comment by SDquest** [comment]
Thanks for your interesting. The other columns represent the confident of XGBoost model to classify one contig into virus, plasmid, prokaryote, or eukaryote. We have now added the header in the output file. Please use the new classify_xgb.py file
